config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users, only: [:new, :index, :create]
  resources :links, only: [:index, :create]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :links, only: [:index, :show, :update]
    end
  end
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :title
  validates_presence_of :url
  validates :url, url: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :links
  validates_presence_of :email
  validates_uniqueness_of :email, case_sensitive: false
  validates_presence_of :password_confirmation
end

app/controllers/api/v1/links_controller.rb
module Api
  module V1
    class LinksController < ApiController
      def index
        respond_with Link.all
      end

      def show
        respond_with Link.find(params[:id])
      end

      def update
        link = Link.find(params[:id])
        respond_with link.update(link_params)
      end

      private
        def link_params
          params.permit("read", "url", "title")
        end
    end
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  protect_from_forgery with: :null_session
  respond_to :json
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    if current_user.nil?
      redirect_to root_path
    else
      @link = Link.new
      @links = current_user.links.all
    end
  end

  def create
    @link = current_user.links.new(link_params)

    if @link.save
      flash.now[:success] = "Link saved!"
      render "index"
    else
      flash.now[:danger] = @link.errors.full_messages.join(', ')
      render "index"
    end
  end

  private

    def link_params
      params.require(:link).permit(:title, :url)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome #{user.email}!"
      redirect_to links_path
    else
      flash.now[:danger] = "Incorrect login details"
      render "new"
    end
  end

  def destroy
    flash[:success] = "You have been logged out"
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "Your account has been successfully created #{@user.email}!"
      session[:user_id] = @user.id
      redirect_to links_path
    else
      flash[:danger] = @user.errors.full_messages.join(', ')
      redirect_to root_path
    end
  end

  private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thoughtbox</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1"></head>
<body>
  <nav>
    <h1>Thoughtbox!</h1>
  </nav>
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>

  <div class="container">
    <% if current_user %>
      <%= link_to "Home", root_path %>
      <%= link_to "Links", links_path %>
      <%= link_to "Log Out", logout_path, method: :delete %>
    <% end %>
    <%= yield %>
  </div>

  <%= javascript_include_tag 'application' %>
</body>
</html>

app/views/links/index.html.erb
<h3>Links Page</h3>

<form class="row">
  <%= text_field_tag 'search', nil, placeholder: 'Search...', class: "form-control",
    id: 'search-bar' %>
</form>

<div class="row">
  <button class="btn btn-default" id="sort-asc" onclick="sortAlphabetically()">
    Sort alphabetically
  </button>
  <button class="btn btn-default" id="filter-read" onclick="filterLinksRead()">
    Links Read
  </button>
  <button class="btn btn-default" id="filter-unread" onclick="filterLinksUnread()">
    Links Unread
  </button>
</div>

<div class="row">
  <h3>Create a new link</h3>
  <%= form_for @link, url: links_path do |f| %>
  <%= f.label :title  %>
  <%= f.text_field :title  %>

  <%= f.label :url  %>
  <%= f.text_field :url  %>

  <%= f.submit "Submit Link" %>
  <% end %>
</div>

<h3>All links</h3>
<div class="links">
  <% unless @links.nil? || @links.empty? %>
    <ul>
      <% @links.each do |link| %>
        <div class="link" id="<%= link.id %>">
          <% if link.read == true %>
            <li id="<%= link.id %>-link">
              <p class="link-title"><strong><%= link.title %>: </strong></p>
              <p id="<%= link.id %>-link-url" class="link-url read-link"><%= link.url %></p>
            </li>
            <button class="btn btn-default hide" id="<%= link.id %>-read">Mark as Read</button>
            <button class="btn btn-default" id="<%= link.id %>-unread">Mark as Unread</button>
          <% else %>
            <li id="<%= link.id %>-link">
              <p class="link-title"><strong><%= link.title %>: </strong></p>
              <p id="<%= link.id %>-link-url" class="link-url"><%= link.url %></p>
            </li>
            <button class="btn btn-default" id="<%= link.id %>-read">Mark as Read</button>
            <button class="btn btn-default hide" id="<%= link.id %>-unread">Mark as Unread</button>
          <% end %>
          <button class="btn btn-default" id="<%= link.id %>-edit">Edit</button>
        </div>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>Create an Account</h1>

<%= form_for @user do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.text_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.text_field :password_confirmation %>

  <%= f.submit "Create Account" %>
<% end %>

app/views/welcome/index.html.erb
<h3>Log In or Sign Up</h3>

<%= link_to "Sign Up", new_user_path %>
<%= link_to "Log In", login_path %>